### ISSUE TITLE
builders(constructor, ...types) does not produce expected output.

### ISSUE THREAD

**Issue by K4rakara** [mudgen/webscript#17]
Given that builders second argument `...types` uses the spread operator, one would think that you could supply several strings for it to use, but it instead outputs a builder for every single character of the supplied name. See attached image
![image](https://user-images.githubusercontent.com/40474474/83980343-eff35b80-a8e2-11ea-8476-38ed30014ec5.png)

**Comment by mudgen** [comment]
@K4rakara The builder's second argument `type` doesn't use the spread operator.   The second argument to `webscript` needs to be an array as in your `main` example.

**Comment by K4rakara** [comment]
Ah, my bad then. I thought it used the spread operator. Probably should have checked before submitting an issue :sweat_smile:
