### ISSUE TITLE
Icon?

### ISSUE THREAD

**Issue by clsource** [mudgen/webscript#6]
Hello maybe you already have an icon for webscript. But if not then maybe using something from Flaticon can help :)

Here are some selections.

![imagen](https://user-images.githubusercontent.com/292738/83066439-0c65dd00-a033-11ea-83a6-216a31b8e0e2.png)

https://www.flaticon.com/free-icon/script_541532?term=script&page=1&position=90

![imagen](https://user-images.githubusercontent.com/292738/83066664-65357580-a033-11ea-83fe-11b6a94fd5a2.png)
https://www.flaticon.com/free-icon/coding_1906567?term=programming&page=1&position=90

Or maybe with the "Deno" fever a dinosaur could be

![imagen](https://user-images.githubusercontent.com/292738/83067179-2f44c100-a034-11ea-8149-7899249b1eb7.png)

https://www.flaticon.com/free-icon/happy_817745?term=happy&page=1&position=67

👍

**Comment by mudgen** [comment]
Yes!  Need an icon!

**Comment by clsource** [comment]
I will close this for now :)

**Comment by mudgen** [comment]
Need an icon.

**Comment by kartiknair** [comment]
Pulled something up in a few minutes, inspired by the greats (javascript, ecmascript, typescript, & wasm). What do you think?

![Frame 11](https://user-images.githubusercontent.com/49618293/83604406-2a799300-a587-11ea-8201-8e10b079acf3.png)
![Frame 12](https://user-images.githubusercontent.com/49618293/83604409-2b122980-a587-11ea-929b-19d4217810af.png)
![Frame 13](https://user-images.githubusercontent.com/49618293/83604412-2c435680-a587-11ea-8c5e-6b4d983d2751.png)

**Comment by mudgen** [comment]
Nice, thank you!
